/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    UiLoadingScreenLoadingScreen: typeof import('./components/ui/LoadingScreen/LoadingScreen.vue')['default'];
    UiMainLogoLogo: typeof import('./components/ui/MainLogo/Logo.vue')['default'];
    UiMainLogoMainLogo: typeof import('./components/ui/MainLogo/MainLogo.vue')['default'];
    'UiMainLogoMainLogo.spec': typeof import('./components/ui/MainLogo/MainLogo.spec.vue')['default'];
  }
}
